/**
 * Media Model — Tracks all uploaded media with SEO metadata.
 *
 * Stores ALT text generated by AI, original filenames, dimensions,
 * and context information for the Admin Media Library.
 */

import mongoose, { Schema, Document } from "mongoose";

export interface IMedia extends Document {
    url: string;
    thumbUrl: string | null;
    filename: string;
    originalFilename: string | null;
    altText: string;
    altTextStatus: "pending" | "generated" | "failed";
    type: "image" | "video";
    format: string | null;
    width: number | null;
    height: number | null;
    sizeBytes: number | null;
    uploadedBy: string | null; // userId or "admin"
    context: string | null; // e.g., "restaurant-gallery", "profile-pic", "review"
    createdAt: Date;
    updatedAt: Date;
}

const MediaSchema = new Schema<IMedia>(
    {
        url: { type: String, required: true, unique: true, index: true },
        thumbUrl: { type: String, default: null },
        filename: { type: String, required: true, index: true },
        originalFilename: { type: String, default: null },
        altText: { type: String, default: "" },
        altTextStatus: {
            type: String,
            enum: ["pending", "generated", "failed"],
            default: "pending",
        },
        type: { type: String, enum: ["image", "video"], default: "image" },
        format: { type: String, default: null },
        width: { type: Number, default: null },
        height: { type: Number, default: null },
        sizeBytes: { type: Number, default: null },
        uploadedBy: { type: String, default: null },
        context: { type: String, default: null },
    },
    {
        timestamps: true,
    }
);

// Text index for search in Admin Media Library
MediaSchema.index({ filename: "text", originalFilename: "text", altText: "text" });

export default mongoose.model<IMedia>("Media", MediaSchema);
