import mongoose, { Schema, Document } from "mongoose";

/**
 * RestaurantInvoice — Monthly settlement invoice for each restaurant.
 *
 * Generated by a CRON job on the 1st of every month for the previous month.
 * Aggregates:
 *   - FoodiePay bookings → platform fee already collected at payment time
 *   - Cash bookings → platform fee accumulated as outstanding balance
 *
 * Prime Partner restaurants (isPrimePartner = true) pay Rs. 0 platform fee
 * on all bookings. This is their incentive to enable Prime.
 *
 * All amounts in PAISA (integer).
 */

export const INVOICE_STATUSES = [
    "Draft",     // Being generated, not yet finalized
    "Pending",   // Finalized, waiting for restaurant to pay
    "Paid",      // Restaurant has settled the invoice
    "Overdue",   // Past due date (30 days after generation)
    "Waived",    // Admin waived the invoice (promotional)
] as const;
export type InvoiceStatus = (typeof INVOICE_STATUSES)[number];

export interface IRestaurantInvoice extends Document {
    restaurantId: mongoose.Types.ObjectId;
    month: string;  // "2026-03"

    // ── Summary Counts ──
    totalBookings: number;
    totalCovers: number;
    totalFoodiePayBookings: number;
    totalCashBookings: number;

    // ── Revenue ──
    totalBillValuePaisa: number;         // Sum of all originalBillPaisa
    totalFoodiePayBillsPaisa: number;    // Bills paid via FoodiePay
    totalCashBillsPaisa: number;         // Bills paid at restaurant

    // ── Platform Fees ──
    totalFoodiePayFeePaisa: number;      // 3% of FoodiePay bills (already collected)
    totalCashFeePaisa: number;           // 3% of cash bills (outstanding)
    isPrimePartner: boolean;             // If true, all fees = 0

    // ── Settlement ──
    totalOutstandingPaisa: number;       // What restaurant owes (cash fees only)
    status: InvoiceStatus;
    dueDate: Date;
    paidAt: Date | null;
    paymentReference: string;            // Bank transfer ref / JazzCash txn id
    paidViaPaisa: number;                // Amount actually received

    // ── Admin ──
    waivedBy: mongoose.Types.ObjectId | null;
    waivedReason: string;
    notes: string;
}

const RestaurantInvoiceSchema = new Schema<IRestaurantInvoice>(
    {
        restaurantId: {
            type: Schema.Types.ObjectId,
            ref: "Restaurant",
            required: true,
        },
        month: { type: String, required: true }, // "2026-03"

        // Summary
        totalBookings: { type: Number, default: 0 },
        totalCovers: { type: Number, default: 0 },
        totalFoodiePayBookings: { type: Number, default: 0 },
        totalCashBookings: { type: Number, default: 0 },

        // Revenue
        totalBillValuePaisa: { type: Number, default: 0 },
        totalFoodiePayBillsPaisa: { type: Number, default: 0 },
        totalCashBillsPaisa: { type: Number, default: 0 },

        // Platform Fees
        totalFoodiePayFeePaisa: { type: Number, default: 0 },
        totalCashFeePaisa: { type: Number, default: 0 },
        isPrimePartner: { type: Boolean, default: false },

        // Settlement
        totalOutstandingPaisa: { type: Number, default: 0 },
        status: { type: String, enum: INVOICE_STATUSES, default: "Draft" },
        dueDate: { type: Date, required: true },
        paidAt: { type: Date, default: null },
        paymentReference: { type: String, default: "" },
        paidViaPaisa: { type: Number, default: 0 },

        // Admin
        waivedBy: { type: Schema.Types.ObjectId, ref: "User", default: null },
        waivedReason: { type: String, default: "" },
        notes: { type: String, default: "" },
    },
    { timestamps: true }
);

// ── Indexes ──
RestaurantInvoiceSchema.index({ restaurantId: 1, month: 1 }, { unique: true });
RestaurantInvoiceSchema.index({ status: 1, dueDate: 1 }); // CRON: overdue check
RestaurantInvoiceSchema.index({ month: 1, status: 1 });    // Admin: monthly overview

export const RestaurantInvoice =
    mongoose.models.RestaurantInvoice ||
    mongoose.model<IRestaurantInvoice>("RestaurantInvoice", RestaurantInvoiceSchema);
