import mongoose, { Schema, Document } from "mongoose";

/**
 * Settlement — Weekly financial settlement record for a restaurant.
 * Generated by a CRON job every Sunday at midnight.
 *
 * Calculates: Revenue - Commission - CoinRedemptions = Net Payable
 */

export const SETTLEMENT_STATUSES = [
    "Pending",
    "Processing",
    "Paid",
    "Disputed",
] as const;

export type SettlementStatus = (typeof SETTLEMENT_STATUSES)[number];

export interface ISettlement extends Document {
    restaurantId: mongoose.Types.ObjectId;
    periodStart: Date; // Monday
    periodEnd: Date; // Sunday
    totalBookings: number;
    totalPax: number;
    totalGrossRevenue: number; // sum of all completed reservation bills
    totalCommission: number; // gross × commission rate
    totalCoinRedemptions: number; // coins redeemed in PKR
    totalBankPromosCost: number; // bank-funded discounts (not charged to restaurant)
    netPayable: number; // gross - commission - coinRedemptions
    commissionRate: number; // snapshot of the rate used
    status: SettlementStatus;
    paymentRef?: string; // bank transfer ref
    paidAt?: Date;
    invoicePdfUrl?: string;
    notes: string;
}

const SettlementSchema = new Schema<ISettlement>(
    {
        restaurantId: {
            type: Schema.Types.ObjectId,
            ref: "Restaurant",
            required: true,
        },
        periodStart: { type: Date, required: true },
        periodEnd: { type: Date, required: true },
        totalBookings: { type: Number, default: 0 },
        totalPax: { type: Number, default: 0 },
        totalGrossRevenue: { type: Number, default: 0 },
        totalCommission: { type: Number, default: 0 },
        totalCoinRedemptions: { type: Number, default: 0 },
        totalBankPromosCost: { type: Number, default: 0 },
        netPayable: { type: Number, default: 0 },
        commissionRate: { type: Number, default: 0.03 },
        status: {
            type: String,
            enum: SETTLEMENT_STATUSES,
            default: "Pending",
        },
        paymentRef: { type: String },
        paidAt: { type: Date },
        invoicePdfUrl: { type: String },
        notes: { type: String, default: "" },
    },
    { timestamps: true }
);

SettlementSchema.index({ restaurantId: 1, periodStart: -1 });
SettlementSchema.index({ status: 1 });

export const Settlement =
    mongoose.models.Settlement ||
    mongoose.model<ISettlement>("Settlement", SettlementSchema);
